version: "3"
services:
  devcontainer:
    container_name: devcontainer
    build:
      context: .
      target: development
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ".:/srv"
    environment:
      - "NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-}"
      - "CUDA_DEVICE_ORDER=PCI_BUS_ID"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,utility"
      - "TF_FORCE_GPU_ALLOW_GROWTH=true"
      - "TF_GPU_THREAD_MODE=gpu_private"
      - "TF_CPP_MIN_LOG_LEVEL=2"
