version: "3"
services:
  devcontainer:
    container_name: devcontainer
    build:
      context: .
      target: dev-stage
      args:
        - USERNAME=${USER}
    ports:
      - 6007:6007
    runtime: nvidia
    environment:
      - "TF_FORCE_GPU_ALLOW_GROWTH=true"
      - "CUDA_DEVICE_ORDER=PCI_BUS_ID"
      - "NVIDIA_VISIBLE_DEVICES=${GPUS}"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,utility"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - workspace:/workspace
      - .:/workspace:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw

volumes:
  workspace:
