version: "3"
services:
  devcontainer:
    build:
      context: .
      target: dev-stage
      args:
        - USERNAME=${USER}
    ports:
      - 6006:6006
    runtime: nvidia
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:rw
