version: "3"
services:
  devcontainer:
    build:
      context: .
      args:
        - USERNAME=${USER}
    runtime: nvidia
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:rw
      - /var/run/docker.sock:/var/run/docker.sockee
